name: fauna_dart_driver
description: A dart implementation of the faunaDB (fauna.com) driver that supports streaming
version: 0.0.1
homepage: https://github.com/pressw-corp/offline-frontend
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  http2: ^2.0.1
  universal_html: ^2.0.8
  synchronized: ^3.0.0+3
  faunadb_http:
    git:
      url: git@github.com:pressw-llc/faunadb-http-dart.git
      ref: master

  http: ^1.2.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
